### ISSUE TITLE
Viewport Size

### ISSUE THREAD

**Issue by levidurfee** [levidurfee/ampbin#60]
Adjustable viewport size of the preview

/cc @lannka

**Comment by lannka** [comment]
Thanks @levidurfee ! This will be super helpful for AMPHTML ads preview

**Comment by levidurfee** [comment]
You can now adjust the viewport of the preview window. Let me know if you think that is intuitive enough.

**Comment by lannka** [comment]
is it pushed out? I don't see any control like that

**Comment by levidurfee** [comment]
I just purged the cache from the CDN.

![image](https://user-images.githubusercontent.com/10798199/48103596-e3d28400-e1fd-11e8-8443-ab5a83889b4f.png)

**Comment by lannka** [comment]
See it now. Thx!

If I understand correctly, only the width can be adjusted as percentage.
I was actually thinking to have both width & height adjustable as absolute pixel numbers.

For AMP page, I'd like to adjust the dimensions to popular phone screen sizes (iPhone X, Pixel 3, etc).
For AMPHTML ads, I'd like to adjust the dimensions to popular ad sizes (300 x 250, etc).

For UI, it will be cool if there is a dropdown menu for a list of preset.

Does it make any sense?

Thanks again for the quick work!

**Comment by levidurfee** [comment]
You can do it with percentage or pixel, but I can change it be popular
screen sizes in a drop-down.

It makes perfect sense!

And I'm happy someone is using the site ☺️

**Comment by lannka** [comment]
For your reference, some popular ad sizes on the web: https://support.google.com/adsense/answer/6002621?visit_id=636771617958422768-1155222561&rd=1
